#!/bin/bash
RMSDIR=~/RMS_data

cd $RMSDIR

if [ "$1" == "start" ]
then
  for PODS in `ls -d * | grep -v baseconfig`
  do
    echo Starting $PODS
    podman start $PODS
  done
  exit 0
fi

if [ "$1" == "stop" ]
then
  for PODS in `ls -d * | grep -v baseconfig`
  do
    echo Stopping $PODS
    podman stop $PODS
  done
  exit 0
fi

if [ "$1" == "bounce" ]
then
  for PODS in `ls -d * | grep -v baseconfig`
  do
    podman stop $PODS
    sleep 60
    podman start $PODS
  done
  exit 0
fi


echo "Usage: podcontrol start/stop"

