#!/bin/bash
cd ~
mkdir -p ~/.config/systemd/user
crontab -l >  crontab

cd ~/RMS_data
for STATION in `ls -d * | grep -v baseconfig`
do
  cd ~/.config/systemd/user
  podman generate systemd --new --name $STATION -f
  systemctl --user daemon-reload
  systemctl --user enable container-$STATION


  # Add restart to cron
  echo 22 12 \* \* \* podman stop $STATION >> ~/crontab
done

cd ~
crontab crontab
rm crontab
