#!/bin/bash

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y podman podman-toolbox podman-compose podman-docker

sudo loginctl enable-linger `whoami`
sudo su - -c "echo `whoami` >> /etc/cron.allow"
echo export XDG_RUNTIME_DIR=/run/user/`id -u` >> ~/.bashrc

chmod u+x ~/rms_container/*_rms


