#!/bin/bash
# We are installing things in usr local bin for all users
# this requires root
if [ `whoami` != "root" ]
then
  echo Run as root
  exit 1
fi

# The username running the pods must be given
if [ $# -eq 0 ]
then
  echo Usage: install_skyfit [username running the RMS containers]
  exit 1
fi

apt-get update 
apt-get install -y python3-virtualenv python3-opencv dpkg-dev build-essential libjpeg-dev libtiff-dev libsdl1.2-dev  libgstreamer-plugins-base1.0-dev libnotify-dev libglut3.12 freeglut3-dev libwebkitgtk-6.0-dev libghc-gtk3-dev python3-tk python3-numpy python3-six python3-scipy python3-pil python3-imageio python3-astropy python3-pil.imagetk

# Install scripts for all cameras
for CAMERA in `find /home/$1/rms_container -name vRMS`
CAMERANAME=`echo $CAMERA | cut -f 5 -d '/'`
do
# Install SkyFit2 start script
cat >/usr/local/bin/skyfit2_$CAMERANAME <<EOF
#!/bin/bash
WHEREIAM=\$PWD
cd $CAMERA
cd ../source/RMS
source $CAMERA/bin/activate
python3 -m Utils.SkyFit2 -c /home/$1/rms_container/$CAMERANAME/source/RMS/.config \$@
cd \$WHEREIAM
EOF
chmod 755 /usr/local/bin/skyfit2_$CAMERA

cat >/usr/local/bin/cameracontrol_$CAMERA <<EOF
#!/bin/bash
WHEREIAM=\$PWD
cd $CAMERA
cd ../source/RMS
source $CAMERA/bin/activate
python3 -m Utils.CameraControl -c /home/$1/rms_container/$CAMERANAME/source/RMS/.config \$@ 
cd \$WHEREIAM
EOF
chmod 755 /usr/local/bin/cameracontrol_$CAMERA

cat >/usr/local/bin/showlivestream_$CAMERA <<EOF
#!/bin/bash
WHEREIAM=\$PWD
cd $CAMERA
cd ../source/RMS
source $CAMERA/bin/activate
python3 -m Utils.ShowLiveStream -c /home/$1/rms_container/$CAMERANAME/source/RMS/.config \$@
cd \$WHEREIAM
EOF
chmod 755 /usr/local/bin/showlivestream_$CAMERA
done

