#!/bin/bash
cd ~
mkdir -p ~/.config/systemd/user
crontab -l >  crontab

cd ~/rms_container
for STATION in `find . -name vRMS | cut -f 2 -d '/'`
do
  cd ~/.config/systemd/user
  podman generate systemd --new --name $STATION -f
  systemctl --user daemon-reload
  systemctl --user enable container-$STATION


  # Add restart to cron
  echo 22 12 \* \* \* podman stop $STATION >> ~/crontab
done

cd ~
crontab crontab
rm crontab
